// templates/default/src/App.svelte
<script lang="ts">
  import { type Story, type TemplateOptions, fromParsed } from "../../../src";
  import StoryPlayer from "./lib/StoryPlayer.svelte";

  let story: Story | undefined = $state();
  let options: TemplateOptions | undefined = $state();

  $effect(() => {
    const originalTitle = document.title;

    const searchParams = new URLSearchParams(location.search);
    const debugParam = searchParams.get("debug");

    const templateOptions = typeof window.TEMPLATE_OPTIONS === "string" ? {} : window.TEMPLATE_OPTIONS;
    if (debugParam !== null) {
      templateOptions.debug = debugParam === "1";
    }

    options = templateOptions;

    const parsedStory = typeof window.PARSED_STORY === "string" ? window.PLACEHOLDER_STORY : window.PARSED_STORY;
    fromParsed(parsedStory).then((s) => {
      document.title = s.title;
      story = s;
    });

    return () => {
      document.title = originalTitle;
    };
  });
</script>

<div class="min-h-screen flex flex-col *:grow">
  {#if story}
    <StoryPlayer {story} {options} />
  {/if}
</div>

// html-template/src/App.tsx
import { Story, fromParsed } from "../../";
import { useEffect, useMemo, useState } from "react";

import StoryPlayer from "./components/StoryPlayer";
import { unescapeHtml } from "./utils";

export default function App() {
  const [story, setStory] = useState<Story>();
  const debug = useMemo(() => new URLSearchParams(window.location.search).get("debug") === "1", []);

  useEffect(() => {
    const originalTitle = document.title;

    const sourceScript = document.querySelector<HTMLScriptElement>("#parsed-story")!;
    const parsedStory = JSON.parse(unescapeHtml(sourceScript.textContent!));
    fromParsed(parsedStory).then((story) => {
      document.title = story.title;
      setStory(story);
    });

    return () => {
      document.title = originalTitle;
    };
  }, []);

  return <>{story && <StoryPlayer story={story} debug={debug} />}</>;
}
