// templates/default/src/lib/StoryPlayer.svelte
<script lang="ts">
  import { tick } from "svelte";
  import { type PromptProps, type Story, type StoryPrompt, type TemplateOptions } from "../../../../src";
  import FcInput from "./FcInput.svelte";
  import { processHtml } from "./process-html";

  // Keep reference to prevent tree-shaking of the custom element registration
  void FcInput;

  interface Props {
    story: Story;
    options?: TemplateOptions;
  }

  let { story, options = {} }: Props = $props();

  let scenes: PromptProps[] = $state([]);

  let lastSceneRef: HTMLDivElement | null = $state(null);
  let lastFormRef: HTMLFormElement | null = $state(null);
  let lastCoverRef: HTMLDivElement | null = $state(null);

  let resolver: ((formData: FormData) => void) | null = null;

  // Scroll to latest scene + play cover animation when scenes change
  $effect(() => {
    const count = scenes.length;
    if (count === 0) {
      return;
    }

    tick().then(() => {
      // Scroll the latest scene into view
      if (lastSceneRef) {
        lastSceneRef.scrollIntoView({ behavior: "smooth", block: "start" });
      }

      // Animate the cover overlay on the latest scene
      if (lastCoverRef) {
        lastCoverRef.animate([{ top: "-100%" }, { top: "100%" }], { duration: 1000 });
      }
    });
  });

  const prompt: StoryPrompt = async (scene) => {
    if (!scene.text && scene.inputs.length === 0 && scene.navs.length === 0) {
      resolver = null;
      return;
    }

    scenes.push(scene);

    return new Promise<FormData>((resolve) => {
      resolver = resolve;
    });
  };

  $effect(() => {
    const timer = setTimeout(() => {
      story.play(prompt, { adapter: "html", debug: options.debug });
    }, 200);
    return () => clearTimeout(timer);
  });

  function resolveForm(form: HTMLFormElement, submitter?: HTMLElement | null) {
    if (resolver) {
      const formData = new FormData(form, submitter);
      resolver(formData);
      resolver = null;
    }
  }

  function handlePlayerClick() {
    if (!lastFormRef) {
      return;
    }

    const lastScene = scenes[scenes.length - 1];
    if (lastScene.navs.length) {
      return;
    }

    resolveForm(lastFormRef);
  }

  function handleFormKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter") {
      e.preventDefault();
    }
  }

  function handleFormSubmit(e: SubmitEvent) {
    e.preventDefault();
    resolveForm(e.currentTarget as HTMLFormElement, e.submitter);
  }
</script>

<svelte:head>
  {#if story.stylesheet}
    <svelte:element this={"style"}>
      {@html story.stylesheet}
    </svelte:element>
  {/if}
</svelte:head>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div class="px-2 md:px-12 pb-[33vh]" onclick={handlePlayerClick}>
  {#each scenes as { text }, i}
    {@const enabled = i === scenes.length - 1}
    <div
      class="scene-container relative px-2 pt-8 first:pt-4 md:first:pt-8 pb-8 first:mt-0 border-b-2 border-red-700 last:border-none overflow-hidden {!enabled
        ? 'opacity-50'
        : ''}"
      bind:this={lastSceneRef}
    >
      <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
      <form
        class="scene-form"
        bind:this={lastFormRef}
        onkeydown={handleFormKeyDown}
        onsubmit={enabled ? handleFormSubmit : (e) => e.preventDefault()}
      >
        {@html processHtml(text, !enabled)}
      </form>
      {#if enabled}
        <div
          class="scene-cover absolute left-0 right-0 top-full h-[200%] bg-linear-to-b from-transparent via-white to-white z-10"
          bind:this={lastCoverRef}
        ></div>
      {/if}
    </div>
  {/each}
</div>

// html-template-old/src/components/StoryPlayer.tsx
import { Story, StoryPrompt } from "../../../";
import { memo, SyntheticEvent, KeyboardEvent, useLayoutEffect, useRef, useState } from "react";
import parse, { domToReact, DOMNode, HTMLReactParserOptions, Element as ParserElement } from "html-react-parser";
import { produce } from "immer";

import FcInput from "./FcInput";

const useParserOptions = (enabled: boolean): HTMLReactParserOptions => ({
  replace(node) {
    if (node.type === "tag") {
      node = node as ParserElement;
      if (node.tagName === "input") {
        const { type, name, value, checked } = node.attribs;
        return (
          <FcInput
            className="
              mx-1 [&.fc-input-text]:border-b-2 [&.fc-input-text]:border-red-700
              [&_.fc-circle]:border-2 [&_.fc-circle]:border-red-700 [&_.fc-circle]:rounded-full
              [&.fc-input-text]:has-disabled:bg-red-100
            "
            type={type}
            name={name}
            defaultValue={value}
            defaultChecked={checked !== undefined}
            disabled={!enabled}
          />
        );
      } else if (node.tagName === "button") {
        const { type, name, value } = node.attribs;
        return (
          <button
            className="mx-0.5 text-red-600 hover:text-red-400 active:text-red-300 disabled:text-red-600 underline cursor-pointer"
            type={type as "button" | "submit" | "reset" | undefined}
            name={name}
            value={value}
            disabled={!enabled}
          >
            {domToReact(node.childNodes as DOMNode[], useParserOptions(enabled))}
          </button>
        );
      }
    }
  },
});

const FormBody = memo(({ html, enabled }: { html: string; enabled: boolean }) => {
  return parse(html, useParserOptions(enabled));
});

type SceneLog = {
  html: string;
};

export default function StoryPlayer({ story, debug }: { story: Story; debug?: boolean }) {
  const [stage, setStage] = useState<"ready" | "started" | "ended">("ready");
  const [scenes, setScenes] = useState<SceneLog[]>([]);

  const sceneRef = useRef<HTMLDivElement>(null);
  const sceneCoverRef = useRef<HTMLDivElement>(null);
  const resolveRef = useRef<(formData: FormData) => void>(null);

  useLayoutEffect(() => {
    const scene = sceneRef.current;
    const cover = sceneCoverRef.current;
    if (scene) {
      scene.scrollIntoView({ behavior: "smooth", block: "start" });
    }
    if (cover) {
      const animation = cover.animate([{ top: "-100%" }, { top: "100%" }], { duration: 1000 });
      animation.play();
    }
  }, [scenes]);

  const prompt: StoryPrompt = async ({ text }) => {
    setScenes(
      produce((draft) => {
        draft.push({ html: text });
      }),
    );
    return new Promise((resolve) => {
      resolveRef.current = resolve;
    });
  };

  const handleCoverClick = () => {
    story.play(prompt, { renderer: "html", debug }).then(() => setStage("ended"));
    setStage("started");
  };

  const handleFormKeyDown = (ev: KeyboardEvent<HTMLFormElement>) => {
    if (ev.key === "Enter") {
      ev.preventDefault();
    }
  };

  const handleFormSubmit = (ev: SyntheticEvent<HTMLFormElement, SubmitEvent>) => {
    ev.preventDefault();
    if (resolveRef.current) {
      const formData = new FormData(ev.currentTarget, ev.nativeEvent.submitter);
      resolveRef.current(formData);
      resolveRef.current = null;
    }
  };

  return (
    <div className="px-2 md:px-12">
      <div>
        {scenes.map(({ html }, i) => {
          const enabled = stage === "started" && i === scenes.length - 1;
          return (
            <div
              key={i}
              ref={enabled ? sceneRef : undefined}
              className={`relative px-2 pt-8 first:pt-4 md:first:pt-8 pb-8 last:pb-[33vh] first:mt-0 border-b-2 border-red-700 last:border-none overflow-hidden ${
                !enabled ? "opacity-50" : ""
              }`}
            >
              <form
                className="chapter-form"
                onKeyDown={handleFormKeyDown}
                onSubmit={enabled ? handleFormSubmit : (ev) => ev.preventDefault()}
              >
                <FormBody html={html} enabled={enabled} />
              </form>
              {enabled && (
                <div
                  ref={sceneCoverRef}
                  className="absolute left-0 right-0 top-[100%] h-[200%] bg-linear-[to_bottom,transparent_0%,#ffffff_50%,#ffffff_100%] z-10"
                ></div>
              )}
            </div>
          );
        })}
      </div>
      {stage === "ready" && (
        <div
          className="fixed inset-0 flex flex-col justify-center items-center text-4xl leading-0 select-none backdrop-blur-xs z-10 after:content-[''] after:h-16"
          onClick={handleCoverClick}
        >
          Click to start
        </div>
      )}
    </div>
  );
}
